package tactician_v1;

import battlecode.common.Direction;
import battlecode.common.MapLocation;

public class Precomp {
    public static final Direction[] DIRS = {
            Direction.NORTH,
            Direction.NORTHEAST,
            Direction.EAST,
            Direction.SOUTHEAST,
            Direction.SOUTH,
            Direction.SOUTHWEST,
            Direction.WEST,
            Direction.NORTHWEST
    };

    public static final MapLocation[] SIGHT_VECS = {
            new MapLocation(-2, -4),
            new MapLocation(-1, -4),
            new MapLocation(0, -4),
            new MapLocation(1, -4),
            new MapLocation(2, -4),
            new MapLocation(-3, -3),
            new MapLocation(-2, -3),
            new MapLocation(-1, -3),
            new MapLocation(0, -3),
            new MapLocation(1, -3),
            new MapLocation(2, -3),
            new MapLocation(3, -3),
            new MapLocation(-4, -2),
            new MapLocation(-3, -2),
            new MapLocation(-2, -2),
            new MapLocation(-1, -2),
            new MapLocation(0, -2),
            new MapLocation(1, -2),
            new MapLocation(2, -2),
            new MapLocation(3, -2),
            new MapLocation(4, -2),
            new MapLocation(-4, -1),
            new MapLocation(-3, -1),
            new MapLocation(-2, -1),
            new MapLocation(-1, -1),
            new MapLocation(0, -1),
            new MapLocation(1, -1),
            new MapLocation(2, -1),
            new MapLocation(3, -1),
            new MapLocation(4, -1),
            new MapLocation(-4, 0),
            new MapLocation(-3, 0),
            new MapLocation(-2, 0),
            new MapLocation(-1, 0),
            new MapLocation(0, 0),
            new MapLocation(1, 0),
            new MapLocation(2, 0),
            new MapLocation(3, 0),
            new MapLocation(4, 0),
            new MapLocation(-4, 1),
            new MapLocation(-3, 1),
            new MapLocation(-2, 1),
            new MapLocation(-1, 1),
            new MapLocation(0, 1),
            new MapLocation(1, 1),
            new MapLocation(2, 1),
            new MapLocation(3, 1),
            new MapLocation(4, 1),
            new MapLocation(-4, 2),
            new MapLocation(-3, 2),
            new MapLocation(-2, 2),
            new MapLocation(-1, 2),
            new MapLocation(0, 2),
            new MapLocation(1, 2),
            new MapLocation(2, 2),
            new MapLocation(3, 2),
            new MapLocation(4, 2),
            new MapLocation(-3, 3),
            new MapLocation(-2, 3),
            new MapLocation(-1, 3),
            new MapLocation(0, 3),
            new MapLocation(1, 3),
            new MapLocation(2, 3),
            new MapLocation(3, 3),
            new MapLocation(-2, 4),
            new MapLocation(-1, 4),
            new MapLocation(0, 4),
            new MapLocation(1, 4),
            new MapLocation(2, 4),
    };

    public static final MapLocation[] ATTACK_VECS = {
            new MapLocation(0, -3),
            new MapLocation(-2, -2),
            new MapLocation(-1, -2),
            new MapLocation(0, -2),
            new MapLocation(1, -2),
            new MapLocation(2, -2),
            new MapLocation(-2, -1),
            new MapLocation(-1, -1),
            new MapLocation(0, -1),
            new MapLocation(1, -1),
            new MapLocation(2, -1),
            new MapLocation(-3, 0),
            new MapLocation(-2, 0),
            new MapLocation(-1, 0),
            new MapLocation(0, 0),
            new MapLocation(1, 0),
            new MapLocation(2, 0),
            new MapLocation(3, 0),
            new MapLocation(-2, 1),
            new MapLocation(-1, 1),
            new MapLocation(0, 1),
            new MapLocation(1, 1),
            new MapLocation(2, 1),
            new MapLocation(-2, 2),
            new MapLocation(-1, 2),
            new MapLocation(0, 2),
            new MapLocation(1, 2),
            new MapLocation(2, 2),
            new MapLocation(0, 3),
    };

    public static final boolean[][] DEF_PATTERN = {
            {false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false},
            {false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true},
            {true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false},
            {false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true},
            {true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false},
            {false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true},
            {true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false},
            {false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false},
            {true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false},
            {false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true},
            {false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false},
            {false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true},
            {true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false},
            {false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true},
            {true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false},
            {false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true},
            {true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false},
            {false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false},
            {true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false},
            {false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true},
            {false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false},
            {false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true},
            {true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false},
            {false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true},
            {true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false},
            {false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true},
            {true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false},
            {false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false},
            {true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false},
            {false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true},
            {false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false},
            {false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true},
            {true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false},
            {false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true},
            {true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false},
            {false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true},
            {true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false},
            {false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false},
            {true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false},
            {false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true},
            {false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false},
            {false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true},
            {true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false},
            {false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true},
            {true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false},
            {false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true},
            {true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false},
            {false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false},
            {true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false},
            {false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true},
            {false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false},
            {false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true},
            {true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false},
            {false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true},
            {true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false},
            {false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true},
            {true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false},
            {false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false},
            {true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false},
            {false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, false, true, false, true, false, true},
    };
}
